In [4]:
import numpy as np
x=np.array([2,4,6,8,10,12,14,16,18,20])
z=np.where(x%4==2)
print(z)
zz=np.where(x+6==10)
print(zz)

y=np.array([[2,4,6]
           ,[3,6,9]])
a=np.where((y%4==0))
print(a)

(array([0, 2, 4, 6, 8], dtype=int64),)
(array([1], dtype=int64),)
(array([0], dtype=int64), array([1], dtype=int64))


In [ ]:
#### searchsorted

x=np.array([2,4,6,8,10])
y=np.searchsorted(x,7,side='right')
print(y)
z=np.array([1,2,3,5,3,5,2])
print(np.searchsorted(z,4))

3
3


In [3]:
import numpy as np 
x=np.array([2,4,6,8,10])
a=np.searchsorted(x,7)
b=np.searchsorted(x,7,side='right')
print(a)
print(b)

x=np.array([1,2,3,4,5,6,7,6,7])
a=np.searchsorted(x,6)
b=np.searchsorted(x,6,side='right')
print(a)
print(b)

3
3
5
8


In [ ]:
########### SORTING ARRAYS ##########
import numpy as np
x=np.array(['aaple','aaaple','aple'])
y=np.array([[3,1,7,]
            ,[2,9,1]])
z=np.array([[[3,2,1],
             [5,3,7]],
             [[5,9,2],
              [4,7,1]]])
w=np.array([True,False,True])
print(np.sort(x),"\n\n")      # sorting alphabetical
print(np.sort(y),"\n\n")       # sorting numeric
print(np.sort(z),"\n\n")       # sorting numeric
print(np.sort(w),"\n\n")       ## sortng boolean

In [ ]:
print(np.sort(z,axis=0))
print("\n",np.sort(z,axis=1))
print("\n", np.sort(z,axis=2))

In [18]:
#### argsort
print(np.argsort(y))

[[1 0 2]
 [2 0 1]]
