In [ ]:
### numpy data types
## checking the data types of array
import numpy as np 

# float
x=np.array([[1.0,3.3],[6.8,7.9]])
print(x.dtype)

# integer
y=np.array([[1,3],[6,7]])
print(y)
print(y.dtype)

float64
[[ True  True]
 [ True  True]]
bool


In [ ]:
#DEFINING data types of existing array
import numpy as np
x=np.array([1,2,3],dtype="str")    # defining data type at the time of creating
y=np.array(["0","1",'-1'])         # creating a array
Y=y.astype('bool')     # converting data type of a existing array ie y
print(x ,x.dtype)
print(Y ,Y.dtype)
print(len(np.sctypeDict.keys()))    # # Shows all dtype names

In [ ]:
## Copy and view
import numpy as np
x=np.array([1,2,3,4])
c=x.copy()   ##in copy , if we change data value in c in does noot affect x
v=x.view()   ## in view. if we change data value in v it affects x
c[0]=12
v[0]=12
print(x)

[12  2  3  4]


In [ ]:
### Numpy Array Shape
import numpy as np 
x=np.array([1,2,3])
y=np.array([[1,2,3],
            [4,5,6]])
z=np.array([[1,2,3],
            [4,5,6]],ndmin=5)
print(z)
print(x.shape)
print(y.shape)
print(z.shape)



In [ ]:
#### reshaping
import numpy as np 
x=np.array([1,2,3,4,5,6])
y=x.reshape((3,2))   ## reshaping into a 2d aray 
print(y)
print(x.reshape(-1,3))
z=np.array([[[1,2,3],
             [4,5,6]],
             [[7,8,9],
             [10,11,12]]])
print(z.reshape(-1))       # flattening an array into 1d array 

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
